name: Action Test23

on: 
  workflow_dispatch:
    inputs:
      unk:
        description: 'stub input'
        required: false
        default: false


jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Test foreground
      uses: yar293709/helllio@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
    # ngrok should exit now
    - name: Test background
      uses: yar293709/helllio@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
        foreground: false
    # ngrok should be still running, so this should not create new ngrok, but should detects ngrok exit correctly
    - name: Test foreground
      uses: yar293709/helllio@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
    # post check should be working
    - name: Test background
      uses: yar293709/helllio@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: Aa123456
        foreground: false
